. "$HOME/.config/powershell/config/core.ps1"
. "$HOME/.config/powershell/config/functions.ps1"
. "$HOME/.config/powershell/config/keybinds.ps1"
. "$HOME/.config/powershell/config/aliases.ps1"
. "$HOME/.config/powershell/config/mise.ps1"